### ISSUE TITLE
Mouseover only shows an error

### ISSUE THREAD

**Issue by bellexandria** [SavedInstances/SavedInstances#218]
I've been getting this on mouseover of the minimap icon, and it no longer shows the overview. I tried resetting saved data, but that did not fix the issue. I'm running 8.0.9.

```
Date: 2019-01-20 21:54:25
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\SavedInstances\SavedInstances.lua line 3875:
   attempt to index field '?' (a nil value)
Debug:
   SavedInstances\SavedInstances.lua:3875: ShowTooltip()
   SavedInstances\SavedInstances.lua:2427: OnEnter()
   ...\AddOns\Details\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:77:
      ...\AddOns\Details\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60
Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 localarr#categoryrow = <table> {
 }
 EnableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 HeaderFont = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3325
 CancelTimer = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:147
 RequestLockInfo = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2522
 localarr#blankrow = <table> {
 }
 TRADE_SKILL_LIST_UPDATE = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:4376
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 EncounterEnd = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2625
 localarr#columns = <table> {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 ADDON_LOADED = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2502
 RegisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 RegisterBucketEvent = <function> defined @Interface\AddOns\HandyNotes_TimelessIsleChests\libs\AceBucket-3.0\AceBucket-3.0.lua:184
 memcheck = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2868
 scan_item_cds = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:4269
 localarr#showcol = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 RegisterEvent = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 localarr#RefreshTemp = <table> {
 }
 IterateModules = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 TradeSkillRescan = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:4355
 CHAT_MSG_MONSTER_YELL = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2593
 localarr#wbsave = <table> {
 }
 OnInitialize = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2351
 NewModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 ShowTooltip = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3337
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:172
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:160
 toonInit = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2335
 SendMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 GetName = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 localarr#instancerow = <table> {
 }
 QuestRefresh = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2880
 localarr#lfrbox = <table> {
 }
 name = "SavedInstances_Core"
 localarr#instancesaved = <table> {
 }
 RegisterBucketMessage = <function> defined @Interface\AddOns\HandyNotes_TimelessIsleChests\libs\AceBucket-3.0\AceBucket-3.0.lua:200
 orderedModules = <table> {
 }
 localarr#categoryshown = <table> {
 }
 Disable = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 scale = 1
 Enable = <function> defined @Interface\AddOns\DataStore\libs\AceA
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  ACP, vr259 
  AllTheThings, v1.8.2b
  Altoholic, vr190
  AngryKeystones, v
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  AzeritePowerWeights, v8.1.7
  AzeriteTooltip, v1.92
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BigDebuffs, vv7.3
  CanIMogIt, v8.0.0v1.13
  Castbars, v
  ClickGrats, v8.0.1.1
  Clique, vv80000-1.0.0
  CollectMe, v2.10.1
  Coordinates, v2.05
  CursorTrail, v8.0.1.1
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMArchaeology, v
  DBMCore, v8.1.2
  DBMDefaultSkin, v
  DBMInterrupts, v7.3.0
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DressingRoomFunctions, vv1.5.0
  eAlignUpdated, v8.0.1
  Enchantrix, v8.0.6158 (SwimmingSeadragon)
  ExRT, v4000
  HandyNotes, vv1.5.3
  HandyNotesAchievements, v0.4.22
  HandyNotesAzerothsTopTunes, vv1.2.2
  HandyNotesBattleForAzerothAchievments, vv7
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.45
  HandyNotesHigherLearning, v8.0.0.0
  HandyNotesLostAndFound, v1
  HandyNotesPandariaTreasures, v1.06
  HandyNotesTimelessIsleRareElites, v2.32
  HandyNotesTimelessIsleChests, v1.21
  HandyNotesTimelessTreasures, v1.0.7
  HandyNotesWarfrontRares, v0.5.0
  Informant, v8.0.6159 (SwimmingSeadragon)
  NomiCakes, v8.0.0.1
  NPCScan, v8.0.1.13
  Omen, v3.2.0
  OPie, vVanilla 9
  Overachiever, v1.0.5
  OverachieverCache, v1.0.5
  Paste, v1.4.10
  Pawn, v2.2.34
  PersonalLootHelper, v2.19
  Postal, vv3.6.0
  ProfessionAssistance, v3.5.6-HotFix
  QEDungeonTips, v4.9.0
  RaidAchievement, v
  RaidAchievementOldModules, v
  RaiderIO, v8.1.0 (v201901200600)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  RaiderIODBUSH, v
  RaiderIODBUSHR, v
  RelicInspector, v3.0
  RepHelper, v8.0.0.5-release
  SavedInstances, v8.0.9
  ShadowedUnitFrames, vv4.2.1
  SimpleArmory, v0.0.6
  Simulationcraft, v1.10.10
  Stubby, v8.0.6161 (SwimmingSeadragon)
  TellMeWhen, v8.5.9
  TheUndermineJournal, v5.4.20190119
  TipTac, v18.08.20
  TipTacItemRef, v18.08.12
  TipTacTalents, v18.07.30
  TomCats, v1.0.1
  TomTom, vv80001-1.0.2
  TransmogCraftsman, v7.0.3.7
  TransmogSetProgress, v8.0.01
  WarfrontRareTracker, v0.9.7
  WeakAuras, v2.11.0
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.1.0.80100 <none>
  (ck=c61)
```

**Comment by LiangYuxuan** [comment]
I think it's like #214 , but it was solved suddenly. Could you reinstall addon and try if it is still bug?

**Comment by bellexandria** [comment]
Reinstall did not fix it :(

Its around the code with dealing with emissaries, so I was wondering if there's changes coming around that that weren't announced?

**Comment by LiangYuxuan** [comment]
Please try latest alpha :)

**Comment by bellexandria** [comment]
Thank you, I will check this out!

**Comment by bellexandria** [comment]
Yes, that fixed it completely. Thank you so much!
