### ISSUE TITLE
LibQTip LUA errors since 10.1.3 release

### ISSUE THREAD

**Issue by citna** [SavedInstances/SavedInstances#754]
**Describe the bug**

Scanning my mouse over progress sections going up and down on the SavedInstances window from the minimap icon causes LUA errors
**Do you have an error log of what happened?**
 
1x SavedInstances/Core/Core.lua:1942: Invalid frame provided.
[string "=[C]"]: ?
[string "@REFlex/Libs/LibQTip-1.0-49/LibQTip-1.0.lua"]:1531: in function `SmartAnchorTo'
[string "@SavedInstances/Core/Core.lua"]:1942: in function `_OnEnter_func'
[string "@REFlex/Libs/LibQTip-1.0-49/LibQTip-1.0.lua"]:1357: in function <...rfaceREFlex/Libs/LibQTip-1.0/LibQTip-1.0.lua:1351>

Locals:
(*temporary) = "Invalid frame provided."

Then with Reflex disabled: 
2x SavedInstances/Core/Core.lua:1942: Invalid frame provided.
[string "=[C]"]: ?
[string "@SavedInstances/Libs/LibQTip-1.0-49/LibQTip-1.0.lua"]:1531: in function `SmartAnchorTo'
[string "@SavedInstances/Core/Core.lua"]:1942: in function `_OnEnter_func'
[string "@SavedInstances/Libs/LibQTip-1.0-49/LibQTip-1.0.lua"]:1357: in function <...dOns/SavedInstances/Libs/LibQTip-1.0/LibQTip-1.0.lua:1351>

Locals:
(*temporary) = "Invalid frame provided."

**To Reproduce**
 
Open SI from minimap icon, mouse over going up and down on a character's progress sections and you receive the LUA error.
**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I did turn off all addons other than BugGrabber and BugSack with SavedInstances for the same LUA error as the 2nd one I posted.
**Which version of SavedInstances are you using?**
10.1.4/10.1.3
**Was it working in a previous version? If yes, which was the last good one?**
10.1.2 before the tooltip func commit
**Additional context**
The LUA error doesn't seem to cause any functionality problems that I notice. I just prefer to not have LUA errors :).

Also the Progress module could use two lines added into the Sparks of Life section to be fully tracking all current quests. I could submit a PR if you'd like or it's just adding 74871, -- The Forbidden Reach
	  75305, -- Zaralek Cavern at line 785.

**Comment by Stanzilla** [comment]
That was fixed in 10.1.4

**Comment by citna** [comment]
Still occurs on 10.1.4 for me. I deleted the addon and reinstalled it for the same result. Do I need to deleted the savedvariables file as well?

I tested again just now and to be more specific than before with how to repeat the error, it's when I mouse over the "Roll Bonus" section.

**Comment by LiangYuxuan** [comment]
related to _Roll Bonus_ hover function
